---
title: Jekyll Materialize
email: your-email@domain.com
author: hugocarreira
author_github: hugocarreira
description: |
  a simple theme for Jekyll using Materializecss
baseurl: ""
url: https://vtcuong95.github.io
paginate: 12
github:
  user: vtcuong95
  repository: vtcuong95.github.io
  url: https://vtcuong95.github.io
  status: true
home_bgfile: bg.jpg
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
